package ProjectApps;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ate
 */

import ProjectLibs.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class AddEquipment extends javax.swing.JFrame {

    String tableName = "PapersOffice";
    String name, username;
    JDBCSingleton jdbc= JDBCSingleton.getInstance();
    PurchasesReport purchasesTable = new PurchasesReport();
    int count = 0, quantity = 0, price = 0, totalPrice = 0;
    
    /**
     * Creates new form AddEquipment
     */
    public AddEquipment() {
        initComponents();
        jTable1.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(0,0,0));
        jTable1.getTableHeader().setForeground(new Color(255, 255, 255));
        jTable1.getTableHeader().setDefaultRenderer(new HeaderColor());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel2.setBackground(new Color(0, 0, 0, 0));
    }

    
     public class HeaderColor extends DefaultTableCellRenderer {

        public HeaderColor() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
           
           setBackground(new java.awt.Color(0,0,0));
            return this;
        }

    }
     
    
     
    public boolean checkInputs()
    {
        if(jTextField1.getText() == null
            || jTextField2.getText() == null
            || jTextField3.getText() == null
            || String.valueOf(jComboBox1.getSelectedIndex()) == null
            || jTextField3.getText() == null
          ){
            return false;
        }
        else{
            try{
                Float.parseFloat(jTextField3.getText());
                return true;
            }catch(Exception ex)
            {
                return false;
            }
        }
    }
    
    public void ShowEquipmentTable() throws SQLException, ClassNotFoundException
    {
        ArrayList<Equipment> list = jdbc.getTableList(tableName);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[4];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getAssetcondition();
            row[3] = list.get(i).getQuantity();
            
            model.addRow(row);
        }
    }
    
    public void ShowPurchasesTable() throws SQLException, ClassNotFoundException
    {
        ArrayList<DamageReportDetails> list = jdbc.getPurchasesList(tableName);
        DefaultTableModel model = (DefaultTableModel)purchasesTable.getjTable1().getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getAssetcondition();
            row[3] = list.get(i).getQuantity();
            row[4] = list.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    
    protected void updateState() {
        boolean enabled = jComboBox1.getSelectedItem().equals("Lost/Disposed equipment");
        jTextField4.setEnabled(enabled );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtHelp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price of the equipment");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        txtHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/helpb.png"))); // NOI18N
        txtHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtHelpMousePressed(evt);
            }
        });
        jPanel2.add(txtHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Condition of the equipment");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID of the equipment");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name of the equipment");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit_button.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("X");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modifyb.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/deleteb.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insertb.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good condition", "Needs repair", "For replacement", "Lost/Disposed equipment" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 220, 22));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/genb.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 220, -1));

        jTextField2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 220, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Office Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 460, -1));

        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextField3.setOpaque(false);
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 210, -1));

        jTextField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextField4.setEnabled(false);
        jTextField4.setOpaque(false);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 210, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity of equipment");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Condition", "Quantity"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(153, 0, 153));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 460, 280));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add_equip_window.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, 950, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            jdbc.createEquipmentList(tableName);
            jdbc.createPurchasesList(tableName);
            if (tableName == "PapersOffice") {
                jLabel6.setText("Papers Office");
            }
            else if (tableName == "CommunicationsOffice") {
                jLabel6.setText("Communications Office");
            }
            else if (tableName == "HeadOffice") {
                jLabel6.setText("Head Office");
            }
            ShowEquipmentTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            for (double i = 0.0; i <= 1.0; i = i + 0.1) 
        {
            String val = i + "";
            float f = Float.valueOf(val); 
            this.setOpacity(f);
            
            try {
                Thread.sleep(30);
            }
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
            
         ImageIcon notifs = new ImageIcon ("src/Images/icons8_wrench_64px.png");
        JOptionPane.showMessageDialog(this, "Please click HELP in order to know how the system works.", "NOTICE", JOptionPane.INFORMATION_MESSAGE, notifs);
    }//GEN-LAST:event_formWindowOpened

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        try {
            ShowPurchasesTable();
            purchasesTable.name = name;
            purchasesTable.username = username;
            purchasesTable.setVisible(true);
            purchasesTable.tableName = tableName;
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel11MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        updateState();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // BUTTON FOR ADDING EQUIPMENT TO THE LIST
        IFactory conditionFactory = new ConditionFactory();
        ICondition condition = conditionFactory.doSomething(jComboBox1.getSelectedIndex());
        int ID = 0;
        quantity = Integer.parseInt(jTextField3.getText());

        if(checkInputs())
        {
            try {
                count = jdbc.countRows(tableName);
                if (count < 5) {

                    ID = jdbc.insert(tableName, jTextField2.getText(), condition.conditionName(), jTextField3.getText());

                    if(jComboBox1.getSelectedItem().equals("Lost/Disposed equipment")){
                        price = Integer.parseInt(jTextField4.getText());
                        totalPrice = quantity * price;
                        jdbc.insertPurchases(tableName, String.valueOf(totalPrice), ID);
                    }

                   ImageIcon bell = new ImageIcon ("src/Images/icons8_bell_64px.png");
                   JOptionPane.showMessageDialog(this, "EQUIPMENT ADDED", "SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE, bell);
                    ShowEquipmentTable();
                }
                else {
                   ImageIcon bell = new ImageIcon ("src/Images/icons8_private_64px.png");
                   JOptionPane.showMessageDialog(this, "YOU CAN ONLY ADD 5 EQUIPMENT AT A TIME", "STOP", JOptionPane.ERROR_MESSAGE, bell);
                }
            } catch (Exception ex) {
                   ImageIcon bell = new ImageIcon ("src/Images/icons8_unavailable_64px_1.png");
                   JOptionPane.showMessageDialog(this, "COULD NOT ADD EQUIPMENT.", "ERROR", JOptionPane.ERROR_MESSAGE, bell);
            }
        }
        else
        {
                   ImageIcon bell = new ImageIcon ("src/Images/icons8_private_64px.png");
                   JOptionPane.showMessageDialog(this, "YOU MUST COMPLETE ALL THE FORMS.", "ERROR", JOptionPane.ERROR_MESSAGE, bell);
        }
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:

        // BUTTON FOR DELETING EQUIPMENT FROM THE LIST
        if(!jTextField1.getText().equals(""))
        {
            try {
                jdbc.delete(tableName, Integer.parseInt(jTextField1.getText()));
                jdbc.delete(tableName + "_purchasesList", Integer.parseInt(jTextField1.getText()));
                
                   ImageIcon bell = new ImageIcon ("src/Images/icons8_bell_64px.png");
                   JOptionPane.showMessageDialog(this, "EQUIPMENT DELETED", "SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE, bell);
                  
                ShowEquipmentTable();
            } catch (SQLException ex) {
                Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
                   ImageIcon bell = new ImageIcon ("src/Images/icons8_unavailable_64px_1.png");
                   JOptionPane.showMessageDialog(this, "COULD NOT DELETE EQUIPMENT.", "ERROR", JOptionPane.ERROR_MESSAGE, bell);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
                   ImageIcon bell = new ImageIcon ("src/Images/icons8_private_64px.png");
                   JOptionPane.showMessageDialog(this, "ID IS NOT SPECIFIED.", "ERROR", JOptionPane.ERROR_MESSAGE, bell);
        }
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // BUTTON FOR UPDATING EQUIPMENT INFORMATION
        IFactory conditionFactory = new ConditionFactory();
        ICondition condition = conditionFactory.doSomething(jComboBox1.getSelectedIndex());

        if(checkInputs() && jTextField1.getText() != null)
        {
            try {
                Equipment previousRecord = jdbc.getTableRow(tableName, Integer.parseInt(jTextField1.getText()));
                quantity = Integer.parseInt(jTextField3.getText());

                jdbc.update(tableName, Integer.parseInt(jTextField1.getText()), jTextField2.getText(), condition.conditionName(), jTextField3.getText());

                if(previousRecord.getAssetcondition() != "For Replacement" && jComboBox1.getSelectedItem().equals("Lost/Disposed equipment")){
                    price = Integer.parseInt(jTextField4.getText());
                    totalPrice = quantity * price;
                    jdbc.insertPurchases(tableName, String.valueOf(totalPrice), Integer.parseInt(jTextField1.getText()));
                }
                else if(jComboBox1.getSelectedItem().equals("Lost/Disposed equipment")){
                    price = Integer.parseInt(jTextField4.getText());
                    totalPrice = quantity * price;
                    jdbc.updatePurchases(tableName, Integer.parseInt(jTextField1.getText()), jTextField2.getText(), condition.conditionName(), jTextField3.getText(), totalPrice);
                }
                else{
                    jdbc.delete(tableName + "_purchasesList", Integer.parseInt(jTextField1.getText()));
                }

                   ImageIcon bell = new ImageIcon ("src/Images/icons8_bell_64px.png");
                   JOptionPane.showMessageDialog(this, "EQUIPMENT UPDATED", "SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE, bell);
                ShowEquipmentTable();
            } catch (SQLException ex) {
                Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddEquipment.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
                   ImageIcon bell = new ImageIcon ("src/Images/icons8_private_64px.png");
                   JOptionPane.showMessageDialog(this, "YOU MUST COMPLETE ALL THE FORMS.", "ERROR", JOptionPane.ERROR_MESSAGE, bell);
        }
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:

        MenuWindow menu = new MenuWindow();
        menu.setVisible(true);
        menu.pack();
        this.dispose();
    }//GEN-LAST:event_jLabel9MousePressed

    private void txtHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHelpMousePressed
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/Images/icons8_help_64px.png");
        JOptionPane.showMessageDialog(this, "The system implements the INSERT, MODIFY and DELETE process in order to successfully monitor equipment."
                + "\n - To INSERT the equipment, you are required to fill ALL the details EXCEPT for the ID before you press the button. \n ID will be automatically generated."
                + "\n - To MODIFY the equipment, you are required to fill ALL the details INCLUDING the ID before you press the button."
                + "\n - To DELETE the equipment, you will ONLY need to fill or specify the ID."
                + "\n - For the PRICE, you will ONLY need to fill the values in INTEGER, do not specify DOUBLEs (e.g 60.00, 70.00)"
                + "\n - The PRICE field is automatically disabled EXCEPT for the condition of LOST/DISPOSED."
                + "\n - For damage report, click on GENERATE PURCHASE for LOST/DISPOSED equipment."
                + "\n - You are ONLY allowed to ADD 5 EQUIPMENT at a time."
                + "\n NOTE: Each MODIFICATION you make, the OUTPUT will be AUTOMATICALLY generated in the table as an OVERALL report.", "HELP", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_txtHelpMousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jLabel14MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel txtHelp;
    // End of variables declaration//GEN-END:variables
}